/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createValidationMessageResultObjectFromDiscriminatorValue, type ValidationMessageResultObject } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/login
 */
export interface LoginRequestBuilder extends BaseRequestBuilder<LoginRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ValidationMessageResultObject>}
     */
     post(requestConfiguration?: RequestConfiguration<LoginRequestBuilderPostQueryParameters> | undefined) : Promise<ValidationMessageResultObject | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<LoginRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
export interface LoginRequestBuilderPostQueryParameters {
    email?: string;
    password?: string;
}
/**
 * Uri template for the request builder.
 */
export const LoginRequestBuilderUriTemplate = "{+baseurl}/api/user/login{?email*,password*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const LoginRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: LoginRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createValidationMessageResultObjectFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
