/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUserModelResultObjectFromDiscriminatorValue, type UserModelResultObject } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/getUser
 */
export interface GetUserRequestBuilder extends BaseRequestBuilder<GetUserRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UserModelResultObject>}
     */
     get(requestConfiguration?: RequestConfiguration<GetUserRequestBuilderGetQueryParameters> | undefined) : Promise<UserModelResultObject | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<GetUserRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface GetUserRequestBuilderGetQueryParameters {
    id?: string;
}
/**
 * Uri template for the request builder.
 */
export const GetUserRequestBuilderUriTemplate = "{+baseurl}/api/user/getUser{?id*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const GetUserRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: GetUserRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createUserModelResultObjectFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
