/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AuthRequestBuilderNavigationMetadata, type AuthRequestBuilder } from './auth/index.js';
// @ts-ignore
import { LessonRequestBuilderNavigationMetadata, LessonRequestBuilderRequestsMetadata, type LessonRequestBuilder } from './lesson/index.js';
// @ts-ignore
import { type UserRequestBuilder, UserRequestBuilderNavigationMetadata, UserRequestBuilderRequestsMetadata } from './user/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The Auth property
     */
    get auth(): AuthRequestBuilder;
    /**
     * The lesson property
     */
    get lesson(): LessonRequestBuilder;
    /**
     * The user property
     */
    get user(): UserRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    auth: {
        navigationMetadata: AuthRequestBuilderNavigationMetadata,
    },
    lesson: {
        requestsMetadata: LessonRequestBuilderRequestsMetadata,
        navigationMetadata: LessonRequestBuilderNavigationMetadata,
    },
    user: {
        requestsMetadata: UserRequestBuilderRequestsMetadata,
        navigationMetadata: UserRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
