/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithIdRequestBuilder, WithIdRequestBuilderRequestsMetadata } from './withId/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/lesson/api/lesson
 */
export interface LessonRequestBuilder extends BaseRequestBuilder<LessonRequestBuilder> {
    /**
     * Builds and executes requests for operations under /api/lesson/api/lesson/id={id}
     * @param id The path parameter: id
     * @returns {WithIdRequestBuilder}
     */
     withId(id: string | undefined) : WithIdRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const LessonRequestBuilderUriTemplate = "{+baseurl}/api/lesson/api/lesson";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LessonRequestBuilderNavigationMetadata: Record<Exclude<keyof LessonRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    withId: {
        requestsMetadata: WithIdRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/* tslint:enable */
/* eslint-enable */
