/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CheckInRequestBuilderRequestsMetadata, type CheckInRequestBuilder } from './checkIn/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/party
 */
export interface PartyRequestBuilder extends BaseRequestBuilder<PartyRequestBuilder> {
    /**
     * The checkIn property
     */
    get checkIn(): CheckInRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PartyRequestBuilderUriTemplate = "{+baseurl}/api/party";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PartyRequestBuilderNavigationMetadata: Record<Exclude<keyof PartyRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    checkIn: {
        requestsMetadata: CheckInRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
