/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createResumeModelFromDiscriminatorValue, type ResumeModel } from '../../models/index.js';
// @ts-ignore
import { ApiRequestBuilderNavigationMetadata, type ApiRequestBuilder } from './api/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/lesson
 */
export interface LessonRequestBuilder extends BaseRequestBuilder<LessonRequestBuilder> {
    /**
     * The api property
     */
    get api(): ApiRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ResumeModel>}
     */
     get(requestConfiguration?: RequestConfiguration<LessonRequestBuilderGetQueryParameters> | undefined) : Promise<ResumeModel | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<LessonRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface LessonRequestBuilderGetQueryParameters {
    id?: string;
}
/**
 * Uri template for the request builder.
 */
export const LessonRequestBuilderUriTemplate = "{+baseurl}/api/lesson{?id*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const LessonRequestBuilderNavigationMetadata: Record<Exclude<keyof LessonRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    api: {
        navigationMetadata: ApiRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const LessonRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: LessonRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createResumeModelFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
