/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBooleanResultObjectFromDiscriminatorValue, Language, type BooleanResultObject } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/user/changeLanguage
 */
export interface ChangeLanguageRequestBuilder extends BaseRequestBuilder<ChangeLanguageRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BooleanResultObject>}
     */
     post(requestConfiguration?: RequestConfiguration<ChangeLanguageRequestBuilderPostQueryParameters> | undefined) : Promise<BooleanResultObject | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<ChangeLanguageRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
export interface ChangeLanguageRequestBuilderPostQueryParameters {
    language?: Language;
}
/**
 * Uri template for the request builder.
 */
export const ChangeLanguageRequestBuilderUriTemplate = "{+baseurl}/api/user/changeLanguage{?language*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ChangeLanguageRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ChangeLanguageRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createBooleanResultObjectFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
