/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyModelResultObject } from './PartyModelResultObject';
import {
    PartyModelResultObjectFromJSON,
    PartyModelResultObjectFromJSONTyped,
    PartyModelResultObjectToJSON,
    PartyModelResultObjectToJSONTyped,
} from './PartyModelResultObject';

/**
 * 
 * @export
 * @interface AddToQueueResponse
 */
export interface AddToQueueResponse {
    /**
     * 
     * @type {PartyModelResultObject}
     * @memberof AddToQueueResponse
     */
    result?: PartyModelResultObject;
}

/**
 * Check if a given object implements the AddToQueueResponse interface.
 */
export function instanceOfAddToQueueResponse(value: object): value is AddToQueueResponse {
    return true;
}

export function AddToQueueResponseFromJSON(json: any): AddToQueueResponse {
    return AddToQueueResponseFromJSONTyped(json, false);
}

export function AddToQueueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddToQueueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : PartyModelResultObjectFromJSON(json['result']),
    };
}

export function AddToQueueResponseToJSON(json: any): AddToQueueResponse {
    return AddToQueueResponseToJSONTyped(json, false);
}

export function AddToQueueResponseToJSONTyped(value?: AddToQueueResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': PartyModelResultObjectToJSON(value['result']),
    };
}

