/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckInRequest
 */
export interface CheckInRequest {
    /**
     * 
     * @type {string}
     * @memberof CheckInRequest
     */
    id?: string;
}

/**
 * Check if a given object implements the CheckInRequest interface.
 */
export function instanceOfCheckInRequest(value: object): value is CheckInRequest {
    return true;
}

export function CheckInRequestFromJSON(json: any): CheckInRequest {
    return CheckInRequestFromJSONTyped(json, false);
}

export function CheckInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CheckInRequestToJSON(json: any): CheckInRequest {
    return CheckInRequestToJSONTyped(json, false);
}

export function CheckInRequestToJSONTyped(value?: CheckInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

