/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyModelResultObject } from './PartyModelResultObject';
import {
    PartyModelResultObjectFromJSON,
    PartyModelResultObjectFromJSONTyped,
    PartyModelResultObjectToJSON,
    PartyModelResultObjectToJSONTyped,
} from './PartyModelResultObject';

/**
 * 
 * @export
 * @interface CheckInResponse
 */
export interface CheckInResponse {
    /**
     * 
     * @type {PartyModelResultObject}
     * @memberof CheckInResponse
     */
    result?: PartyModelResultObject;
}

/**
 * Check if a given object implements the CheckInResponse interface.
 */
export function instanceOfCheckInResponse(value: object): value is CheckInResponse {
    return true;
}

export function CheckInResponseFromJSON(json: any): CheckInResponse {
    return CheckInResponseFromJSONTyped(json, false);
}

export function CheckInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : PartyModelResultObjectFromJSON(json['result']),
    };
}

export function CheckInResponseToJSON(json: any): CheckInResponse {
    return CheckInResponseToJSONTyped(json, false);
}

export function CheckInResponseToJSONTyped(value?: CheckInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': PartyModelResultObjectToJSON(value['result']),
    };
}

