/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationMessage } from './ValidationMessage';
import {
    ValidationMessageFromJSON,
    ValidationMessageFromJSONTyped,
    ValidationMessageToJSON,
    ValidationMessageToJSONTyped,
} from './ValidationMessage';
import type { PartyModel } from './PartyModel';
import {
    PartyModelFromJSON,
    PartyModelFromJSONTyped,
    PartyModelToJSON,
    PartyModelToJSONTyped,
} from './PartyModel';

/**
 * 
 * @export
 * @interface PartyModelResultObject
 */
export interface PartyModelResultObject {
    /**
     * 
     * @type {Array<PartyModel>}
     * @memberof PartyModelResultObject
     */
    records: Array<PartyModel>;
    /**
     * 
     * @type {Array<ValidationMessage>}
     * @memberof PartyModelResultObject
     */
    messages: Array<ValidationMessage>;
}

/**
 * Check if a given object implements the PartyModelResultObject interface.
 */
export function instanceOfPartyModelResultObject(value: object): value is PartyModelResultObject {
    if (!('records' in value) || value['records'] === undefined) return false;
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function PartyModelResultObjectFromJSON(json: any): PartyModelResultObject {
    return PartyModelResultObjectFromJSONTyped(json, false);
}

export function PartyModelResultObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartyModelResultObject {
    if (json == null) {
        return json;
    }
    return {
        
        'records': ((json['records'] as Array<any>).map(PartyModelFromJSON)),
        'messages': ((json['messages'] as Array<any>).map(ValidationMessageFromJSON)),
    };
}

export function PartyModelResultObjectToJSON(json: any): PartyModelResultObject {
    return PartyModelResultObjectToJSONTyped(json, false);
}

export function PartyModelResultObjectToJSONTyped(value?: PartyModelResultObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'records': ((value['records'] as Array<any>).map(PartyModelToJSON)),
        'messages': ((value['messages'] as Array<any>).map(ValidationMessageToJSON)),
    };
}

