/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WaitingListModelResultObject } from './WaitingListModelResultObject';
import {
    WaitingListModelResultObjectFromJSON,
    WaitingListModelResultObjectFromJSONTyped,
    WaitingListModelResultObjectToJSON,
    WaitingListModelResultObjectToJSONTyped,
} from './WaitingListModelResultObject';

/**
 * 
 * @export
 * @interface WaitingListResponse
 */
export interface WaitingListResponse {
    /**
     * 
     * @type {WaitingListModelResultObject}
     * @memberof WaitingListResponse
     */
    result?: WaitingListModelResultObject;
}

/**
 * Check if a given object implements the WaitingListResponse interface.
 */
export function instanceOfWaitingListResponse(value: object): value is WaitingListResponse {
    return true;
}

export function WaitingListResponseFromJSON(json: any): WaitingListResponse {
    return WaitingListResponseFromJSONTyped(json, false);
}

export function WaitingListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitingListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : WaitingListModelResultObjectFromJSON(json['result']),
    };
}

export function WaitingListResponseToJSON(json: any): WaitingListResponse {
    return WaitingListResponseToJSONTyped(json, false);
}

export function WaitingListResponseToJSONTyped(value?: WaitingListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': WaitingListModelResultObjectToJSON(value['result']),
    };
}

