/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WaitingListRequest
 */
export interface WaitingListRequest {
    /**
     * 
     * @type {string}
     * @memberof WaitingListRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the WaitingListRequest interface.
 */
export function instanceOfWaitingListRequest(value: object): value is WaitingListRequest {
    return true;
}

export function WaitingListRequestFromJSON(json: any): WaitingListRequest {
    return WaitingListRequestFromJSONTyped(json, false);
}

export function WaitingListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitingListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function WaitingListRequestToJSON(json: any): WaitingListRequest {
    return WaitingListRequestToJSONTyped(json, false);
}

export function WaitingListRequestToJSONTyped(value?: WaitingListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

