/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WaitingListModelResultObject } from './WaitingListModelResultObject';
import {
    WaitingListModelResultObjectFromJSON,
    WaitingListModelResultObjectFromJSONTyped,
    WaitingListModelResultObjectToJSON,
    WaitingListModelResultObjectToJSONTyped,
} from './WaitingListModelResultObject';

/**
 * 
 * @export
 * @interface WaitingListMetaDataResponse
 */
export interface WaitingListMetaDataResponse {
    /**
     * 
     * @type {WaitingListModelResultObject}
     * @memberof WaitingListMetaDataResponse
     */
    result?: WaitingListModelResultObject;
}

/**
 * Check if a given object implements the WaitingListMetaDataResponse interface.
 */
export function instanceOfWaitingListMetaDataResponse(value: object): value is WaitingListMetaDataResponse {
    return true;
}

export function WaitingListMetaDataResponseFromJSON(json: any): WaitingListMetaDataResponse {
    return WaitingListMetaDataResponseFromJSONTyped(json, false);
}

export function WaitingListMetaDataResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitingListMetaDataResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : WaitingListModelResultObjectFromJSON(json['result']),
    };
}

export function WaitingListMetaDataResponseToJSON(json: any): WaitingListMetaDataResponse {
    return WaitingListMetaDataResponseToJSONTyped(json, false);
}

export function WaitingListMetaDataResponseToJSONTyped(value?: WaitingListMetaDataResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'result': WaitingListModelResultObjectToJSON(value['result']),
    };
}

