/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyDto } from './PartyDto';
import {
    PartyDtoFromJSON,
    PartyDtoFromJSONTyped,
    PartyDtoToJSON,
    PartyDtoToJSONTyped,
} from './PartyDto';

/**
 * 
 * @export
 * @interface AddToWaitingListRequest
 */
export interface AddToWaitingListRequest {
    /**
     * 
     * @type {PartyDto}
     * @memberof AddToWaitingListRequest
     */
    party?: PartyDto;
}

/**
 * Check if a given object implements the AddToWaitingListRequest interface.
 */
export function instanceOfAddToWaitingListRequest(value: object): value is AddToWaitingListRequest {
    return true;
}

export function AddToWaitingListRequestFromJSON(json: any): AddToWaitingListRequest {
    return AddToWaitingListRequestFromJSONTyped(json, false);
}

export function AddToWaitingListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddToWaitingListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'party': json['party'] == null ? undefined : PartyDtoFromJSON(json['party']),
    };
}

export function AddToWaitingListRequestToJSON(json: any): AddToWaitingListRequest {
    return AddToWaitingListRequestToJSONTyped(json, false);
}

export function AddToWaitingListRequestToJSONTyped(value?: AddToWaitingListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'party': PartyDtoToJSON(value['party']),
    };
}

