/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationMessage } from './ValidationMessage';
import {
    ValidationMessageFromJSON,
    ValidationMessageFromJSONTyped,
    ValidationMessageToJSON,
    ValidationMessageToJSONTyped,
} from './ValidationMessage';
import type { PartyDto } from './PartyDto';
import {
    PartyDtoFromJSON,
    PartyDtoFromJSONTyped,
    PartyDtoToJSON,
    PartyDtoToJSONTyped,
} from './PartyDto';

/**
 * 
 * @export
 * @interface AddToWaitingListResponse
 */
export interface AddToWaitingListResponse {
    /**
     * 
     * @type {Array<ValidationMessage>}
     * @memberof AddToWaitingListResponse
     */
    messages: Array<ValidationMessage>;
    /**
     * 
     * @type {string}
     * @memberof AddToWaitingListResponse
     */
    partyName?: string;
    /**
     * 
     * @type {Array<PartyDto>}
     * @memberof AddToWaitingListResponse
     */
    parties?: Array<PartyDto>;
}

/**
 * Check if a given object implements the AddToWaitingListResponse interface.
 */
export function instanceOfAddToWaitingListResponse(value: object): value is AddToWaitingListResponse {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function AddToWaitingListResponseFromJSON(json: any): AddToWaitingListResponse {
    return AddToWaitingListResponseFromJSONTyped(json, false);
}

export function AddToWaitingListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddToWaitingListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(ValidationMessageFromJSON)),
        'partyName': json['partyName'] == null ? undefined : json['partyName'],
        'parties': json['parties'] == null ? undefined : ((json['parties'] as Array<any>).map(PartyDtoFromJSON)),
    };
}

export function AddToWaitingListResponseToJSON(json: any): AddToWaitingListResponse {
    return AddToWaitingListResponseToJSONTyped(json, false);
}

export function AddToWaitingListResponseToJSONTyped(value?: AddToWaitingListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(ValidationMessageToJSON)),
        'partyName': value['partyName'],
        'parties': value['parties'] == null ? undefined : ((value['parties'] as Array<any>).map(PartyDtoToJSON)),
    };
}

