/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationMessage } from './ValidationMessage';
import {
    ValidationMessageFromJSON,
    ValidationMessageFromJSONTyped,
    ValidationMessageToJSON,
    ValidationMessageToJSONTyped,
} from './ValidationMessage';

/**
 * 
 * @export
 * @interface CancelCheckInResponse
 */
export interface CancelCheckInResponse {
    /**
     * 
     * @type {Array<ValidationMessage>}
     * @memberof CancelCheckInResponse
     */
    messages: Array<ValidationMessage>;
}

/**
 * Check if a given object implements the CancelCheckInResponse interface.
 */
export function instanceOfCancelCheckInResponse(value: object): value is CancelCheckInResponse {
    if (!('messages' in value) || value['messages'] === undefined) return false;
    return true;
}

export function CancelCheckInResponseFromJSON(json: any): CancelCheckInResponse {
    return CancelCheckInResponseFromJSONTyped(json, false);
}

export function CancelCheckInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelCheckInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': ((json['messages'] as Array<any>).map(ValidationMessageFromJSON)),
    };
}

export function CancelCheckInResponseToJSON(json: any): CancelCheckInResponse {
    return CancelCheckInResponseToJSONTyped(json, false);
}

export function CancelCheckInResponseToJSONTyped(value?: CancelCheckInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': ((value['messages'] as Array<any>).map(ValidationMessageToJSON)),
    };
}

