/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyDto } from './PartyDto';
import {
    PartyDtoFromJSON,
    PartyDtoFromJSONTyped,
    PartyDtoToJSON,
    PartyDtoToJSONTyped,
} from './PartyDto';

/**
 * 
 * @export
 * @interface CheckInRequest
 */
export interface CheckInRequest {
    /**
     * 
     * @type {PartyDto}
     * @memberof CheckInRequest
     */
    party: PartyDto;
}

/**
 * Check if a given object implements the CheckInRequest interface.
 */
export function instanceOfCheckInRequest(value: object): value is CheckInRequest {
    if (!('party' in value) || value['party'] === undefined) return false;
    return true;
}

export function CheckInRequestFromJSON(json: any): CheckInRequest {
    return CheckInRequestFromJSONTyped(json, false);
}

export function CheckInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'party': PartyDtoFromJSON(json['party']),
    };
}

export function CheckInRequestToJSON(json: any): CheckInRequest {
    return CheckInRequestToJSONTyped(json, false);
}

export function CheckInRequestToJSONTyped(value?: CheckInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'party': PartyDtoToJSON(value['party']),
    };
}

