/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartyDto
 */
export interface PartyDto {
    /**
     * 
     * @type {string}
     * @memberof PartyDto
     */
    waitingListName?: string;
    /**
     * 
     * @type {string}
     * @memberof PartyDto
     */
    sessionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PartyDto
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PartyDto
     */
    size?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PartyDto
     */
    canCheckIn?: boolean;
}

/**
 * Check if a given object implements the PartyDto interface.
 */
export function instanceOfPartyDto(value: object): value is PartyDto {
    return true;
}

export function PartyDtoFromJSON(json: any): PartyDto {
    return PartyDtoFromJSONTyped(json, false);
}

export function PartyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'waitingListName': json['waitingListName'] == null ? undefined : json['waitingListName'],
        'sessionId': json['sessionId'] == null ? undefined : json['sessionId'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'canCheckIn': json['canCheckIn'] == null ? undefined : json['canCheckIn'],
    };
}

export function PartyDtoToJSON(json: any): PartyDto {
    return PartyDtoToJSONTyped(json, false);
}

export function PartyDtoToJSONTyped(value?: PartyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'waitingListName': value['waitingListName'],
        'sessionId': value['sessionId'],
        'name': value['name'],
        'size': value['size'],
        'canCheckIn': value['canCheckIn'],
    };
}

