/* tslint:disable */
/* eslint-disable */
/**
 * WaitingList
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PartyModel } from './PartyModel';
import {
    PartyModelFromJSON,
    PartyModelFromJSONTyped,
    PartyModelToJSON,
    PartyModelToJSONTyped,
} from './PartyModel';

/**
 * 
 * @export
 * @interface WaitingListModel
 */
export interface WaitingListModel {
    /**
     * 
     * @type {Array<PartyModel>}
     * @memberof WaitingListModel
     */
    parties?: Array<PartyModel>;
    /**
     * 
     * @type {string}
     * @memberof WaitingListModel
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof WaitingListModel
     */
    totalSeatsAvailable?: number;
    /**
     * 
     * @type {number}
     * @memberof WaitingListModel
     */
    timeForService?: number;
    /**
     * 
     * @type {string}
     * @memberof WaitingListModel
     */
    id?: string;
}

/**
 * Check if a given object implements the WaitingListModel interface.
 */
export function instanceOfWaitingListModel(value: object): value is WaitingListModel {
    return true;
}

export function WaitingListModelFromJSON(json: any): WaitingListModel {
    return WaitingListModelFromJSONTyped(json, false);
}

export function WaitingListModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): WaitingListModel {
    if (json == null) {
        return json;
    }
    return {
        
        'parties': json['parties'] == null ? undefined : ((json['parties'] as Array<any>).map(PartyModelFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'totalSeatsAvailable': json['totalSeatsAvailable'] == null ? undefined : json['totalSeatsAvailable'],
        'timeForService': json['timeForService'] == null ? undefined : json['timeForService'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function WaitingListModelToJSON(json: any): WaitingListModel {
    return WaitingListModelToJSONTyped(json, false);
}

export function WaitingListModelToJSONTyped(value?: WaitingListModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'parties': value['parties'] == null ? undefined : ((value['parties'] as Array<any>).map(PartyModelToJSON)),
        'name': value['name'],
        'totalSeatsAvailable': value['totalSeatsAvailable'],
        'timeForService': value['timeForService'],
        'id': value['id'],
    };
}

